### ISSUE TITLE
not recognized

### ISSUE THREAD

**Issue by gabrySerra** [wetcork/raiplay-dl#9]
```
raiplay-dl.py : The term 'raiplay-dl.py' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ raiplay-dl.py -f 1200 https://www.raiplay.it/video/2016/06/Don-Matteo ...
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (raiplay-dl.py:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Can you help me? I'm a beginner

**Comment by Damix48** [comment]
You have to use python: `python raiplay-dl.py`.

Or download the `.exe` [dist/raiplay-windows-latest.exe](https://github.com/wetcork/raiplay-dl/raw/main/dist/raiplay-windows-latest.exe)

**Comment by gabrySerra** [comment]
```
PS C:\Users\Gabriele Lucian\Downloads\raiplay-dl-main (1)\raiplay-dl-main> python raiplay-dl.py
Traceback (most recent call last):
  File "C:\Users\Gabriele Lucian\Downloads\raiplay-dl-main (1)\raiplay-dl-main\raiplay-dl.py", line 12, in <module>
    from natsort import natsorted,ns
ModuleNotFoundError: No module named 'natsort'
PS C:\Users\Gabriele Lucian\Downloads\raiplay-dl-main (1)\raiplay-dl-main>
```

@Damix48  When I run the .exe, Python opens for me for a second, and then instantly closes.

**Comment by gabrySerra** [comment]
```
PS C:\Users\Gabriele\Downloads\raiplay-dl-main (1)\raiplay-dl-main> python raiplay-dl.py
Traceback (most recent call last):
  File "C:\Users\Gabriele\Downloads\raiplay-dl-main (1)\raiplay-dl-main\raiplay-dl.py", line 12, in <module>
    from natsort import natsorted,ns
ModuleNotFoundError: No module named 'natsort'
PS C:\Users\Gabriele\Downloads\raiplay-dl-main (1)\raiplay-dl-main>
```

When I run the .exe, Python opens for me for a second, and then instantly closes.

**Comment by Damix48** [comment]
`pip install -r requirements.txt`

**Comment by gabrySerra** [comment]
Thanks, I was able to run the script.
I hope it gets back to working as soon as possible!
